FROM navikt/node-express:16
USER root
RUN apk --no-cache add curl vips-dev binutils make gcc g++
USER apprunner

COPY --chown=apprunner:apprunner ./yarn.lock ./package.json /var/server/

RUN yarn install

COPY --chown=apprunner:apprunner ./ /var/server/

CMD ["yarn", "start:dev:ts-server"]
