version: "3.4"

x-common-variables: &common-build-variables
  # Trenger auth for mvn clean install, kjør `yarn setup:docker:env` for å konfigurere
  github_username: ${GITHUB_USER}
  github_token: ${GITHUB_TOKEN}

x-common-token-environment: &common-token-environment
  LOGINSERVICE_IDPORTEN_DISCOVERY_URL: http://oauthmock:8080/fake/.well-known/openid-configuration
  # Hardkodet i fakedings for fake idporten
  LOGINSERVICE_IDPORTEN_AUDIENCE: "notfound"
  TOKEN_X_WELL_KNOWN_URL: http://oauthmock:8080/tokenx/.well-known/openid-configuration

x-common-log-config: &common-log-config
  options:
    max-size: 50k

volumes:
  keys:
  secure-logs:

services:
  frontend:
    logging: *common-log-config
    container_name: "frontend"
    build:
      context: ./
      target: webpack-express-deps-builder # Før vi bygger og sletter dev-dependencies
    command: ["yarn", "start:dev:ts-server"]
    environment:
      <<: *common-token-environment
      BASE_PATH: /familie/barnetrygd/soknad/ordinaer/
      ENV: docker-compose
      # FORCE_DISABLED: 1 # Uncomment for å utvikle disabled-appen
    volumes:
      - ./src:/var/server/src
      - secure-logs:/secure-logs
    ports:
      - "3000:3000"
      - "55554:55554"

  frontend-prod:
    profiles:
      - test-prod-build
    logging: *common-log-config
    container_name: "frontend-prod"
    build:
      context: ./
      target: prod-runner # Samme docker image som kjører i preprod og prod
      args:
        base_path: /familie/barnetrygd/soknad/ordinaer/
    environment:
      <<: *common-token-environment
      BASE_PATH: /familie/barnetrygd/soknad/ordinaer/
      ENV: docker-compose-prod
      # FORCE_DISABLED: 1 # Uncomment for å utvikle disabled-appen
    volumes:
      - secure-logs:/secure-logs
    ports:
      - "3000:3000"

  api:
    logging: *common-log-config
    container_name: "soknad-api"
    build:
      context: dockerstuff/soknad-api
      args:
        <<: *common-build-variables
        git_commit: 2ea30669f5ec763a7a506328738d7825fd13c1a5
    depends_on:
      - key_generator
      - oauthmock
    volumes:
      - secure-logs:/secure-logs
      - keys:/keys
    environment:
      <<: *common-token-environment
      TOKEN_X_PRIVATE_JWK: '/keys/familie-ba-soknad-api.json'
      TOKEN_X_CLIENT_ID: 'dev-local:teamfamilie:familie-ba-soknad-api'
      FAMILIE_BA_MOTTAK_URL: 'http://mottak:8090'

  mottak:
    logging: *common-log-config
    container_name: "mottak"
    build:
      context: dockerstuff/mottak
      args:
        <<: *common-build-variables
        git_commit: 3636989ac7f348bac1daef3c92d825ebee631d74
    depends_on:
      - key_generator
      - postgres
      - kafka
      - configurator
      - oauthmock
    volumes:
      - keys:/keys
      - secure-logs:/secure-logs
    environment:
      <<: *common-token-environment
      TOKEN_X_PRIVATE_JWK: '/keys/familie-ba-mottak.json'
      TOKEN_X_CLIENT_ID: 'dev-local:teamfamilie:familie-ba-mottak'
      KAFKA_BROKERS: http://kafka:9092
      FAMILIE_DOKUMENT_API_URL: http://dokument:8082
      FAMILIE_BA_DOKGEN_API_URL: http://dokgen:8080
      FAMILIE_INTEGRASJONER_API_URL: http://journalforing

  dokument:
    logging: *common-log-config
    container_name: "familie-dokument"
    build:
      context: dockerstuff/dokument
      args:
        <<: *common-build-variables
        git_commit: 16125c5016e082f283a525d0e69d2c785f38621e
    depends_on:
      - key_generator
      - oauthmock
    volumes:
      - keys:/keys
      - secure-logs:/secure-logs
    ports:
      - "8082:8082"
    environment:
      <<: *common-token-environment
      TOKEN_X_PRIVATE_JWK: '/keys/familie-dokument.json'
      TOKEN_X_CLIENT_ID: 'dev-local:teamfamilie:familie-dokument'

  dokgen:
    logging: *common-log-config
    container_name: dokgen
    build:
      context: "https://${GITHUB_TOKEN}:@github.com/navikt/familie-ba-dokgen.git#f7ee973be5e808490192813d85e7564c547d49bc"
    environment:
      RUNTIME_OPTS: "--write.access=true"
    ports:
      - "5914:8080"
    volumes:
      - secure-logs:/secure-logs
      # - ../familie-ba-dokgen/content:/app/content
    user: root # ellers klager den så fælt på permissions til /secure-logs

  oauthmock:
    logging: *common-log-config
    container_name: "idporten-ish"
    image: "ghcr.io/navikt/fakedings/fakedings:b1244f187badb294b47e0e3c3042abec91e04658"
    ports:
      - "8083:8080"

  loginservice:
    logging: *common-log-config
    depends_on:
      - oauthmock
    build:
      context: dockerstuff/loginservice
    ports:
      - "8080:80"
    environment:
      FAKEDINGS_ADDRESS: "http://oauthmock:8080"
      TOKEN_COOKIE_NAME: "selvbetjening-idtoken"

  journalforing:
    logging: *common-log-config
    build:
      context: dockerstuff/journalføring
    volumes:
      - ./var/mottatte_soknader:/var/mottatte_soknader
    environment:
      STORAGE_DIRECTORY: /var/mottatte_soknader

  key_generator:
    logging: *common-log-config
    container_name: "jwk-generator"
    # Will generate tokenx keys and then shut down
    build:
      context: dockerstuff/jwker
      args:
        git_commit: 850963d98bfd4e04836212fcb2efb218d56db7f5
    environment:
      APPS: "familie-ba-soknad-api,familie-ba-mottak,familie-dokument"
      KEY_OUTPUT_DIRECTORY: /keys
    volumes:
      - keys:/keys

  configurator:
    logging: *common-log-config
    container_name: "cluster-configurator"
    build:
      context: dockerstuff/configurator
    restart: on-failure
    depends_on:
      - kafka
      - kafkadminrest
    environment:
      KAFKA_ADMIN_ADDRESS: "kafkadminrest:8080"

  testentry:
    logging: *common-log-config
    container_name: "test-entry"
    # Denne er bare hvis du trenger å logge inn i en docker-service for å se om de andre kan nås på det interne nettverket
    image: alpine
    command: ["sleep", "10000000"]
    volumes:
      - keys:/keys
      - secure-logs:/secure-logs

  openldap:
    logging: *common-log-config
    build:
      context: https://github.com/navikt/navkafka-docker-compose.git#:ldap
    container_name: ldap
    ports:
      - "10636:636"
      - "10389:389"
    environment:
      - "LDAP_TLS_VERIFY_CLIENT=try"

  zookeeper:
    logging: *common-log-config
    build:
      context: https://github.com/navikt/navkafka-docker-compose.git#:zookeeper
    container_name: zookeeper
    environment:
      - "ZOOKEEPER_CLIENT_PORT=2181"
      - "ZOOKEEPER_AUTH_PROVIDER_1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
    ports:
      - "2181:2181"

  kafka:
    logging: *common-log-config
    build:
      context: https://github.com/navikt/navkafka-docker-compose.git#:kafka
    container_name: kafka
    restart: unless-stopped
    environment:
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_LISTENERS=SASLPLAINTEXT://0.0.0.0:9092,SASLINTERNAL://kafka:9093"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=SASLPLAINTEXT:SASL_PLAINTEXT,SASLINTERNAL:SASL_PLAINTEXT"
      - "KAFKA_ADVERTISED_LISTENERS=SASLPLAINTEXT://kafka:9092,SASLINTERNAL://kafka:9093"
      - "KAFKA_PROTOCOL_NAME=SASLPLAINTEXT,SASLINTERNAL"
      - "KAFKA_LISTENER_NAME_SASLPLAINTEXT_PLAIN_SASL_SERVER_CALLBACK_HANDLER_CLASS=no.nav.common.security.authentication.SimpleLDAPAuthentication"
      - "KAFKA_LISTENER_NAME_SASLINTERNAL_PLAIN_SASL_SERVER_CALLBACK_HANDLER_CLASS=no.nav.common.security.authentication.SimpleLDAPAuthentication"
      - "KAFKA_AUTHORIZER_CLASS_NAME=no.nav.common.security.authorization.SimpleLDAPAuthorizer"
      - "KAFKA_SUPER_USERS=User:igroup"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=SASLINTERNAL"
      - "KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN"
      - "KAFKA_SASL_ENABLED_MECHANISMS=PLAIN"
      - "KAFKA_DEFAULT_REPLICATION_FACTOR=1"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
      - "KAFKA_AUTO_CREATE_TOPICS_ENABLE=false"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
      - openldap

  kafkadminrest:
    logging: *common-log-config
    image: "navikt/kafka-adminrest"
    ports:
      - "8840:8080"
    environment:
      - "LDAP_CONNTIMEOUT=2000"
      - "LDAP_USERATTRNAME=cn"
      - "LDAP_AUTH_HOST=ldap"
      - "LDAP_AUTH_PORT=636"
      - "LDAP_SRVUSERBASE=OU=ServiceAccounts,DC=test,DC=local"
      - "LDAP_GROUPBASE=OU=kafka,OU=AccountGroupNotInRemedy,OU=Groups,OU=NAV,OU=BusinessUnits,DC=test,DC=local"
      - "LDAP_GROUPATTRNAME=cn"
      - "LDAP_GRPMEMBERATTRNAME=member"
      - "LDAP_USER=igroup"
      - "LDAP_PASSWORD=itest"
      - "KAFKA_BROKERS=kafka:9093"
      - "KAFKA_CLIENTID=kafka-adminrest"
      - "KAFKA_SECURITY=TRUE"
      - "KAFKA_SECPROT=SASL_PLAINTEXT"
      - "KAFKA_SASLMEC=PLAIN"
      - "KAFKA_USER=igroup"
      - "LDAP_HOST=ldap"
      - "LDAP_PORT=636"
      - "LDAP_AUTH_USERBASE=ou=Users,ou=NAV,dc=test,dc=local"
      - "KAFKA_PASSWORD=itest"

  schema-registry:
    logging: *common-log-config
    image: "confluentinc/cp-schema-registry:5.0.1"
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      - "SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=SASL_PLAINTEXT://kafka:9093"
      - "SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM=PLAIN"
      - "SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"igroup\" password=\"itest\";"
      - "SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SASL_PLAINTEXT"
      - "SCHEMA_REGISTRY_HOST_NAME=schema-registry"
      - "SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081"

  postgres:
    logging: *common-log-config
    image: "postgres"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "familie-ba-mottak"
