export enum OmBarnaDineSpørsmålId {
    erNoenAvBarnaFosterbarn = 'er-noen-av-barna-fosterbarn',
    hvemErFosterbarn = 'hvem-er-fosterbarn',
    oppholderBarnSegIInstitusjon = 'oppholder-barn-seg-i-institusjon',
    hvemOppholderSegIInstitusjon = 'hvem-oppholder-seg-i-institusjon',
    erBarnAdoptertFraUtland = 'er-barn-adoptert-fra-utland',
    hvemErAdoptertFraUtland = 'hvem-er-adoptert-fra-utland',
    søktAsylForBarn = 'søkt-asyl-for-barn',
    hvemErSøktAsylFor = 'hvem-er-søkt-asyl-for',
    barnOppholdtSegTolvMndSammenhengendeINorge = 'tolv-mnd-sammenhengende-i-norge',
    hvemTolvMndSammenhengendeINorge = 'hvem-tolv-mnd-sammenhengende-i-norge',
    mottarBarnetrygdForBarnFraAnnetEøsland = 'barnetrygd-fra-annet-eøsland',
    hvemBarnetrygdFraAnnetEøsland = 'hvem-mottar-barnetrygd-eøsland',
    erOppgittAvdødPartnerForelder = 'er-oppgitt-avdød-partner-forelder',
    erFolkeregAvdødEktefelleForelder = 'er-folkeregistrert-avdød-ektefelle-forelder',
    erFolkeregAvdødPartnerForelder = 'er-folkeregistrert-avdød-partner-forelder',
    hvemAvdødPartner = 'hvem-er-avdød-partner-forelder-til',
}
