apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-soknad
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25M"
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  port: 9000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - "https://www.nav.no/familie/barnetrygd/soknad/ordinaer"
    - "https://www.nav.no/familie/barnetrygd/soknad/utvidet"
  accessPolicy:
    outbound:
      rules:
        - application: familie-ba-soknad-api
      external:
        - host: "www.nav.no"
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  envFrom:
    - secret: ba-soknad
    - configmap: loginservice-idporten
  env:
    - name: BASE_PATH
      value: {{base_path}}
  secureLogs:
    enabled: true
