export enum OmDegSpørsmålId {
    'borPåRegistrertAdresse' = 'bor-på-registrert-adresse',
    'telefonnummer' = 'telefonnummer',
    'oppholderSegINorge' = 'oppholder-seg-i-norge',
    'oppholdsland' = 'oppholdsland',
    'oppholdslandDato' = 'oppholdsland-dato',
    'værtINorgeITolvMåneder' = 'vært-i-norge-sammenhengende-tolv-måneder',
    'komTilNorgeDato' = 'kom-til-norge-dato',
    'planleggerÅBoINorgeTolvMnd' = 'planlegger-å-bo-i-norge-sammenhengende-tolv-måneder',
    'erAsylsøker' = 'er-asylsøker',
    'jobberPåBåt' = 'jobber-på-båt',
    'arbeidsland' = 'arbeidsland',
    'mottarUtenlandspensjon' = 'mottar-utenlandspensjon',
    'pensjonsland' = 'pensjonsland',
}

export const omDegSpråkTekstId: Record<OmDegSpørsmålId, string> = {
    [OmDegSpørsmålId.borPåRegistrertAdresse]: 'personopplysninger.spm.riktigAdresse',
    [OmDegSpørsmålId.telefonnummer]: 'personopplysninger.spm.telefonnr',
    [OmDegSpørsmålId.oppholderSegINorge]: 'omdeg.spm.oppholderSegINorge',
    [OmDegSpørsmålId.oppholdsland]: 'omdeg.spm.landopphold',
    [OmDegSpørsmålId.oppholdslandDato]: 'omdeg.spm.landopphold.dato',
    [OmDegSpørsmålId.værtINorgeITolvMåneder]: 'omdeg.spm.vært-i-tolv-måneder',
    [OmDegSpørsmålId.komTilNorgeDato]: 'omdeg.spm.komTilNorge.dato',
    [OmDegSpørsmålId.planleggerÅBoINorgeTolvMnd]: 'omdeg.spm.planlegger-å-bo-i-norge',
    [OmDegSpørsmålId.erAsylsøker]: 'omdeg.spm.erasylsøker',
    [OmDegSpørsmålId.jobberPåBåt]: 'omdeg.spm.jobberpåbåt',
    [OmDegSpørsmålId.arbeidsland]: 'omdeg.spm.hvilket-arbeidsland',
    [OmDegSpørsmålId.mottarUtenlandspensjon]: 'omdeg.spm.mottar-du-pensjon-fra-utland',
    [OmDegSpørsmålId.pensjonsland]: 'omdeg.spm.hvilket-pensjonsland',
};
