import { ESøknadstype } from '../../../../typer/søknad';
import { OmBarnaDineSpørsmålId } from '../../OmBarnaDine/spørsmål';

export const inputISøknad = {
    søknadstype: ESøknadstype.UTVIDET,
    barnInkludertISøknaden: [
        {
            id: '38edcd47-72ab-42d7-ae06-a5d7652c284d',
            navn: 'Barn navn',
            ident: '23456789876',
            alder: '12 år',
            borMedSøker: false,
            adressebeskyttelse: true,
            barnErFyltUt: true,
            utvidet: {
                søkerHarBoddMedAndreForelder: {
                    id: 'søker-har-bodd-med-andre-forelder',
                    svar: 'JA',
                },
                søkerFlyttetFraAndreForelderDato: {
                    id: 'søker-flyttet-fra-andre-forelder-dato',
                    svar: 'UKJENT',
                },
            },
            erFosterbarn: { id: 'hvem-er-fosterbarn', svar: 'JA' },
            erAdoptertFraUtland: { id: 'hvem-er-adoptert-fra-utland', svar: 'JA' },
            erAsylsøker: { id: 'hvem-er-søkt-asyl-for', svar: 'JA' },
            barnetrygdFraAnnetEøsland: {
                id: OmBarnaDineSpørsmålId.hvemBarnetrygdFraAnnetEøsland,
                svar: 'JA',
            },
            oppholderSegIInstitusjon: { id: 'hvem-oppholder-seg-i-institusjon', svar: 'JA' },
            institusjonsnavn: { id: 'institusjonsnavn', svar: 'ints navn' },
            institusjonsadresse: { id: 'institusjonsadresse', svar: 'adresse institusjon' },
            institusjonspostnummer: { id: 'institusjonspostnummer', svar: '4321' },
            institusjonOppholdStartdato: {
                id: 'institusjon-opphold-startdato',
                svar: '2021-07-14',
            },
            institusjonOppholdSluttdato: { id: 'institusjon-opphold-sluttdato', svar: 'UKJENT' },
            oppholderSegIUtland: { id: 'hvem-oppholder-seg-i-utland', svar: 'JA' },
            oppholdsland: { id: 'barn-oppholdsland', svar: 'BHS' },
            oppholdslandSluttdato: { id: 'barn-utenlandsopphold-sluttdato', svar: '2021-08-18' },
            oppholdslandStartdato: { id: 'barn-utenlandsopphold-startdato', svar: '2021-07-13' },
            boddMindreEnn12MndINorge: { id: 'hvem-tolv-mnd-sammenhengende-i-norge', svar: 'NEI' },
            nårKomBarnTilNorgeDato: { id: 'når-kom-barnet-til-norge', svar: '' },
            planleggerÅBoINorge12Mnd: {
                id: 'barn-planlegger-å-bo-sammenhengende-i-norge-12mnd',
                svar: null,
            },
            barnetrygdFraEøslandHvilketLand: { id: 'barnetrygd-hvilket-eøsland', svar: 'AGO' },
            andreForelderNavn: { id: 'andre-forelder-navn', svar: '' },
            andreForelderFnr: { id: 'andre-forelder-fødsels-/dnummer', svar: '' },
            andreForelderFødselsdato: { id: 'andre-forelder-fødselsdato', svar: '' },
            andreForelderArbeidUtlandet: { id: 'andre-forelder-arbeid', svar: null },
            andreForelderArbeidUtlandetHvilketLand: {
                id: 'andre-forelder-arbeid-hvilket-land',
                svar: '',
            },
            andreForelderPensjonUtland: { id: 'andre-forelder-pensjon-utland', svar: null },
            andreForelderPensjonHvilketLand: {
                id: 'andre-forelder-pensjon-hvilket-land',
                svar: '',
            },
            borFastMedSøker: { id: 'bor-barnet-fast-med-deg', svar: 'JA' },
            skriftligAvtaleOmDeltBosted: { id: 'skriftlig-avtale-om-delt-bosted', svar: null },
            søkerForTidsromStartdato: { id: 'søker-for-tidsrom-startdato', svar: '2021-09-08' },
            søkerForTidsromSluttdato: { id: 'søker-for-tidsrom-sluttdato', svar: '2021-09-22' },
        },
    ],
    lestOgForståttBekreftelse: true,
    barnRegistrertManuelt: [],
    dokumentasjon: [
        {
            dokumentasjonsbehov: 'AVTALE_DELT_BOSTED',
            tittelSpråkId: 'dokumentasjon.deltbosted.vedleggtittel',
            beskrivelseSpråkId: 'dokumentasjon.deltbosted.informasjon',
            gjelderForBarnId: [],
            gjelderForSøker: false,
            harSendtInn: false,
            opplastedeVedlegg: [],
        },
        {
            dokumentasjonsbehov: 'VEDTAK_OPPHOLDSTILLATELSE',
            tittelSpråkId: 'dokumentasjon.oppholdstillatelse.vedleggtittel',
            beskrivelseSpråkId: 'dokumentasjon.oppholdstillatelse.informasjon',
            gjelderForBarnId: ['38edcd47-72ab-42d7-ae06-a5d7652c284d'],
            gjelderForSøker: false,
            harSendtInn: false,
            opplastedeVedlegg: [
                {
                    dokumentId: 'f85ef180-ba37-48fd-8153-07060271c347',
                    navn: 'Screenshot 2021-08-13 at 13.04.31.png',
                    størrelse: 810149,
                    tidspunkt: '2021-09-01T11:42:59.852Z',
                },
            ],
        },
        {
            dokumentasjonsbehov: 'ADOPSJON_DATO',
            tittelSpråkId: 'dokumentasjon.adopsjon.vedleggtittel',
            beskrivelseSpråkId: 'dokumentasjon.adopsjon.informasjon',
            gjelderForBarnId: ['38edcd47-72ab-42d7-ae06-a5d7652c284d'],
            gjelderForSøker: false,
            harSendtInn: false,
            opplastedeVedlegg: [
                {
                    dokumentId: '0883c3ec-92a5-4f46-b0d7-6f0cba7bd2f7',
                    navn: 'Screenshot 2021-08-12 at 11.05.12.png',
                    størrelse: 149324,
                    tidspunkt: '2021-09-01T11:42:59.863Z',
                },
            ],
        },
        {
            dokumentasjonsbehov: 'BEKREFTELSE_FRA_BARNEVERN',
            tittelSpråkId: 'dokumentasjon.bekreftelsebarnevernet.vedleggtittel',
            beskrivelseSpråkId: 'dokumentasjon.bekreftelsebarnevernet.informasjon',
            gjelderForBarnId: ['38edcd47-72ab-42d7-ae06-a5d7652c284d'],
            gjelderForSøker: false,
            harSendtInn: false,
            opplastedeVedlegg: [
                {
                    dokumentId: '5ff8ddfe-a568-403a-bec3-a58c22e39504',
                    navn: 'Screenshot 2021-08-23 at 09.39.51.png',
                    størrelse: 115627,
                    tidspunkt: '2021-09-01T11:42:59.867Z',
                },
            ],
        },
        {
            dokumentasjonsbehov: 'BOR_FAST_MED_SØKER',
            tittelSpråkId: 'dokumentasjon.bekreftelseborsammen.vedleggtittel',
            beskrivelseSpråkId: 'dokumentasjon.bekreftelseborsammen.informasjon',
            gjelderForBarnId: ['38edcd47-72ab-42d7-ae06-a5d7652c284d'],
            gjelderForSøker: false,
            harSendtInn: false,
            opplastedeVedlegg: [
                {
                    dokumentId: 'aceb1761-7448-4ed1-87c5-bb3af660cc0d',
                    navn: 'Screenshot 2021-08-27 at 08.54.15.png',
                    størrelse: 153822,
                    tidspunkt: '2021-09-01T11:42:59.870Z',
                },
            ],
        },
        {
            dokumentasjonsbehov: 'SEPARERT_SKILT_ENKE',
            tittelSpråkId: 'dokumentasjon.separasjonskilsmissedødsfall.vedleggtittel',
            beskrivelseSpråkId: 'dokumentasjon.separasjonskilsmissedødsfall.informasjon',
            gjelderForBarnId: [],
            gjelderForSøker: true,
            harSendtInn: false,
            opplastedeVedlegg: [
                {
                    dokumentId: '494b4e7d-3969-4c32-b749-0955bd7be791',
                    navn: 'Screenshot 2021-08-12 at 11.05.12.png',
                    størrelse: 149324,
                    tidspunkt: '2021-09-01T11:42:59.874Z',
                },
            ],
        },
        {
            dokumentasjonsbehov: 'MEKLINGSATTEST',
            tittelSpråkId: 'dokumentasjon.meklingsattest.vedleggtittel',
            beskrivelseSpråkId: 'dokumentasjon.meklingsattest.informasjon',
            gjelderForBarnId: [],
            gjelderForSøker: false,
            harSendtInn: false,
            opplastedeVedlegg: [],
        },
        {
            dokumentasjonsbehov: 'ANNEN_DOKUMENTASJON',
            tittelSpråkId: 'dokumentasjon.annendokumentasjon.vedleggtittel',
            beskrivelseSpråkId: 'dokumentasjon.annendokumentasjon.utvidet.informasjon',
            gjelderForBarnId: [],
            gjelderForSøker: false,
            harSendtInn: false,
            opplastedeVedlegg: [
                {
                    dokumentId: 'ab284204-4081-451d-9784-af084038975e',
                    navn: 'Screenshot 2021-08-23 at 09.39.51.png',
                    størrelse: 115627,
                    tidspunkt: '2021-09-01T11:42:59.877Z',
                },
            ],
        },
    ],
    søker: {
        navn: 'Voksen Voksnessen',
        barn: [
            {
                id: '38edcd47-72ab-42d7-ae06-a5d7652c284d',
                navn: null,
                ident: '23456789876',
                alder: '12 år',
                borMedSøker: false,
                adressebeskyttelse: true,
            },
            {
                id: 'ec49c51c-f87d-46ac-91f5-2cd2e9d344d6',
                navn: 'Barn Barnessen III',
                ident: '12345678987',
                alder: '11 år',
                borMedSøker: true,
                adressebeskyttelse: false,
            },
        ],
        statsborgerskap: [{ landkode: 'NOR' }, { landkode: 'AFG' }],
        ident: '23058518298',
        sivilstand: { type: 'GIFT' },
        adressebeskyttelse: false,
        adresse: {
            adressenavn: 'Solveien',
            postnummer: '2304',
            husnummer: '2',
            husbokstav: 'A',
            bruksenhetnummer: 'H0101',
            bostedskommune: null,
            poststed: 'HAMAR',
        },
        borPåRegistrertAdresse: { id: 'bor-på-registrert-adresse', svar: 'JA' },
        oppholderSegINorge: { id: 'søker-oppholder-seg-i-norge', svar: 'JA' },
        oppholdsland: { id: 'søker-oppholdsland', svar: '' },
        oppholdslandDato: { id: 'søker-oppholdsland-dato', svar: '' },
        værtINorgeITolvMåneder: {
            id: 'søker-vært-i-norge-sammenhengende-tolv-måneder',
            svar: 'JA',
        },
        komTilNorgeDato: { id: 'søker-kom-til-norge-dato', svar: '' },
        planleggerÅBoINorgeTolvMnd: {
            id: 'søker-planlegger-å-bo-i-norge-sammenhengende-tolv-måneder',
            svar: null,
        },
        erAsylsøker: { id: 'er-asylsøker', svar: 'NEI' },
        jobberPåBåt: { id: 'jobber-på-båt', svar: 'NEI' },
        arbeidsland: { id: 'arbeidsland', svar: '' },
        mottarUtenlandspensjon: { id: 'mottar-utenlandspensjon', svar: 'NEI' },
        pensjonsland: { id: 'pensjonsland', svar: '' },
        utvidet: {
            spørsmål: {
                årsak: { id: 'årsak', svar: 'SKILT' },
                separertEnkeSkilt: { id: 'separert-enke-skilt', svar: 'JA' },
                separertEnkeSkiltUtland: { id: 'separert-enke-skilt-utland', svar: 'NEI' },
                separertEnkeSkiltDato: { id: 'separert-enke-skilt-dato', svar: '2021-09-09' },
                harSamboerNå: { id: 'har-samboer-nå', svar: 'JA' },
            },
            nåværendeSamboer: {
                navn: { id: 'utvidet-nåværende-samboer-navn', svar: 'Gunnar' },
                ident: { id: 'utvidet-nåværende-samboer-fnr', svar: 'UKJENT' },
                fødselsdato: { id: 'utvidet-nåværende-samboer-fødselsdato', svar: 'UKJENT' },
                samboerFraDato: {
                    id: 'utvidet-nåværende-samboer-samboerFraDato',
                    svar: '2021-08-11',
                },
            },
            tidligereSamboere: [
                {
                    navn: { id: 'utvidet-tidligere-samboer-navn', svar: 'Donald' },
                    ident: { id: 'utvidet-tidligere-samboer-fnr', svar: 'UKJENT' },
                    fødselsdato: {
                        id: 'utvidet-tidligere-samboer-fødselsdato',
                        svar: '2021-09-02',
                    },
                    samboerFraDato: {
                        id: 'utvidet-tidligere-samboer-samboerFraDato',
                        svar: '2021-08-04',
                    },
                    samboerTilDato: {
                        id: 'utvidet-tidligere-samboer-samboerTilDato',
                        svar: '2021-08-19',
                    },
                },
            ],
        },
    },
    erNoenAvBarnaFosterbarn: { id: 'er-noen-av-barna-fosterbarn', svar: 'JA' },
    oppholderBarnSegIInstitusjon: { id: 'oppholder-barn-seg-i-institusjon', svar: 'JA' },
    erBarnAdoptertFraUtland: { id: 'er-barn-adoptert-fra-utland', svar: 'JA' },
    oppholderBarnSegIUtland: { id: 'oppholder-barn-seg-i-utland', svar: 'JA' },
    søktAsylForBarn: { id: 'søkt-asyl-for-barn', svar: 'JA' },
    barnOppholdtSegTolvMndSammenhengendeINorge: {
        id: 'tolv-mnd-sammenhengende-i-norge',
        svar: 'JA',
    },
    mottarBarnetrygdForBarnFraAnnetEøsland: { id: 'barnetrygd-fra-annet-eøsland', svar: 'JA' },
};
