export enum Årsak {
    SEPARERT = 'SEPARERT',
    SKILT = 'SKILT',
    BRUDD_SAMBOER = 'BRUDD_SAMBOER',
    BODD_ALENE = 'BODD_ALENE',
    ENKE_ENKEMANN = 'ENKE_ENKEMANN',
    FENGSEL_VARETEKT = 'FENGSEL_VARETEKT',
    BRUDD_GIFT = 'BRUDD_GIFT',
    FORVARING = 'FORVARING',
    FORSVUNNET = 'FORSVUNNET',
    PSYKISKHELSEVERN = 'PSYKISKHELSEVERN',
}
