name: Build, push, and deploy app to dev

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'master'

env:
  IMAGE: ghcr.io/${{ github.repository }}/familie-ba-soknad:${{ github.sha }}
  BASE_PATH: /familie/barnetrygd/soknad/ordinaer/

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installer node-pakker
        run: npx yarn
      - name: Kjør typecheck
        run: npx yarn typecheck
      - name: Kjør tester
        env:
          CI: true
        run: npx yarn test

  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg Docker image
        uses: docker/build-push-action@v2
        env:
          DEKORATOREN_URL: "https://dekoratoren.dev.nav.no"
        with:
          tags: ${{ env.IMAGE }}
          build-args: |
            base_path=${{ env.BASE_PATH }}
            sentry_release=${{ github.sha }}
          secrets: |
            sentry_token=${{ secrets.SENTRY_AUTH_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE }}
          build-args: |
            base_path=${{ env.BASE_PATH }}
            sentry_auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}
            sentry_release=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to dev gcp
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_dev.yaml
          VAR: base_path=${{ env.BASE_PATH }}
