name: Build, push, and deploy app to dev

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

env:
  BASE_PATH: /familie/barnetrygd/soknad/ordinaer/
  IMAGE: ghcr.io/navikt/familie-ba-soknad:${{ github.sha }}
  VERSION: familie-ba-soknad:${{ github.sha }}

jobs:
  test:
    name: Kjør typecheck og tester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - name: Installer node-pakker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: yarn --prefer-offline --frozen-lockfile
      - name: Kjør typecheck
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: yarn typecheck
      - name: Kjør tester
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: yarn test

  bygg:
    name: Bygg app/image og push til GitHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
      - name: Yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: yarn --prefer-offline --frozen-lockfile
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ github.sha }}
          BASE_PATH: ${{ env.BASE_PATH }}
          DEKORATOREN_URL: "https://dekoratoren.dev.nav.no"
        run: |
          yarn build
          docker build . -t ${IMAGE}
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE}
  deploy:
    name: Deploy to NAIS
    needs: bygg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy til dev-gcp team namespace
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_dev.yaml
          VAR: VERSION=${{ env.VERSION }}