name: Build, push, and deploy app to dev

on:
  push:
    branches-ignore:
      - 'master'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/familie-ba-soknad:${{ github.sha }}
  BASE_PATH: /familie/barnetrygd/soknad/ordinaer/

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installer node-pakker
        run: npx yarn
      - name: Kjør typecheck
        run: npx yarn typecheck
      - name: Kjør tester
        env:
          CI: true
        run: npx yarn test
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ env.GITHUB_SHA }}
        run: |
          docker build . -t ${IMAGE} -t ${IMAGE_LATEST} --build-arg base_path=${BASE_PATH} --build-arg sentry_auth_token=${SENTRY_AUTH_TOKEN} --build-arg sentry_release=${SENTRY_RELEASE}
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy:
    name: Deploy to dev gcp
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/naiserator_dev.yaml
          VAR: base_path=${{ env.BASE_PATH }}
